<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/blueblood/image/upload/v1554411648/cloud.jpg" alt="blueblood">
                        <h6>blueblood</h6>
                        <p>HTML intermediate</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/blueblood12" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://blueblood.home.blog/" target="_blank"<i class="fab fa-wordpress fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Onwunmelu samuel kelechi a.k.a blueblood</p>
                        <p>i am a mechanical engineer by profession with high interest in programming</p>
                        <p>i joined hng internship to increase my skills</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS3</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
